### ISSUE TITLE
Should this be a plugin?

### ISSUE THREAD

**Issue by pranksinatra** [boonebgorges/wp-cli-git-helper#6]
I noticed this tool is currently distributed as a community package ( https://github.com/wp-cli/wp-cli/wiki/Community-Packages ) and best practices for distributing WP-CLI packages are still being defined ( https://github.com/wp-cli/wp-cli/issues/1564 ).

As a newcomer, I've found it helpful to just use this as a Wordpress plugin by adding a comment:

```
/**
  * Plugin Name: WP-CLI Git Helper
  * Plugin URI: https://github.com/boonebgorges/wp-cli-git-helper
  * Description: Adds the <code>wp gh</code> command, which is a wrapper for <code>wp [plugin|theme] [update|install]</code>.
  * Version: 0.1.0
  * Author: Boone Gorges
  * Author URI: https://boone.gorg.es/
 **/
```

Do you think this would be helpful to others? I don't want to introduce something that doesn't play nice with the evolution of WP-CLI, but it seems to be the approach taken by many other WP-CLI packages at this point.

**Comment by boonebgorges** [comment]
I don't think there's anything wrong with installing this as a plugin on 
specific sites. In general, though, packaging it as a plugin may have 
the effect of limiting its use as a community package.

For the time being, I'd like to continue with the community package 
route, to see if that paradigm sticks. If not, I can think about moving 
to a plugin structure.

**Comment by pranksinatra** [comment]
Sounds good
